Sourcing multiprofile
git-svn-id: https://gum-shell-utils.googlecode.com/svn/trunk@26 ce362bcc-dff7-11de-9129-6395494df245

diff --git a/user/player_cmd b/user/player_cmd
--- a/user/player_cmd
+++ b/user/player_cmd
@@ -1,4 +1,11 @@
 #!/bin/bash
+PROFILE_FILENAME="$( basename $0).conf"
+PROFILES_FILE="/etc/$PROFILE_FILENAME"
+HOME_PROFILES_FILE="$HOME/.$PROFILE_FILENAME"
+if [ -r "$HOME_PROFILES_FILE" ]; then
+	PROFILES_FILE="$HOME_PROFILES_FILE"
+fi
+
 function usage() {
 	echo "Usage: $( basename $0) command [player]"
 	echo "commands supported: "
@@ -15,5 +22,6 @@ CMD="$1"
 shift
 test "x$CMD" == "x" && usage
 
+source $( which multiprofiles) || echo "Dependency missing: multiprofiles (from gum-shell-utils)" && exit 1
 echo "CMD=$CMD; args=$@"
 
